create table
  public.pdga_history (
    id bigint generated by default as identity,
    inserted_at timestamp with time zone not null default now(),
    pdaga_number bigint not null,
    number_members bigint not null,
    constraint pdga_history_pkey primary key (id)
  ) tablespace pg_default;